### ISSUE TITLE
Where to get pretrained ckpt

### ISSUE THREAD

**Issue by xiehuanyi** [avoskou/Stochastic-Transformer-Networks-with-Linear-Competing-Units-Application-to-end-to-end-SL-Translatio#1]
How can I get a pretrained ckpt?

**Comment by avoskou** [comment]
Unfortunately, we don't keep any checkpoints on a public server. I would suggest you download the data and train the model on your local machine; it is relatively easy. If you have any trouble, don't hesitate to contact me via email to share the checkpoints with you.
