### ISSUE TITLE
How to use torchtext.data.Dataset in torchtext version 0.12.0

### ISSUE THREAD

**Issue by JoseMoFi** [avoskou/Stochastic-Transformer-Networks-with-Linear-Competing-Units-Application-to-end-to-end-SL-Translatio#2]

**Comment by JoseMoFi** [comment]
I'm trying to replicate but I can't use the module torchtext.data.Dataset because my version of torchtext is 0.12.0 and its unavailable the version 0.8.0. Someone have an alternative?
I have been searching and I have found that in torchtext==0.12.0 not work because in the version 0.9.0 they moved some packages to legacy dir and in the last version (0.12.0) they remove the legacy dir. 
Thank you.

**Comment by avoskou** [comment]
Hello, the safest way is to use Docker or something similar and install the needed versions.

**Comment by JoseMoFi** [comment]
Hello, thank you for your help, finally I could install an older version of pytorch and this solve my problems! Before I couldn't do it because I have a RTX graphic card and I need use the last version of cuda and when I intalled torchtext==0.8.1 also install the version torch==1.7.1 (which uses <=CUDA102). However, I found this [site](https://pytorch.org/get-started/previous-versions/) which allows install the previous version of PyTorch that you need with CUDA110.
