### ISSUE TITLE
How to process my own dataset?

### ISSUE THREAD

**Issue by Danielgol** [avoskou/Stochastic-Transformer-Networks-with-Linear-Competing-Units-Application-to-end-to-end-SL-Translatio#3]
Hello!

How can I generate the train, test and dev files? I already have the Phoenix dataset (videos and subtitles) and I would like to know how can I generate the files, like the downloaded ones, from scratch, in order to reproduce it in another dataset later.

Thanks!

**Comment by avoskou** [comment]
Hello,
The appropriate data format is a JSON file that contains a sequence of dictionaries, one per video/entry. Each of these dictionaries requires the following keys: 'name' (string),  'signer' (string) , 'gloss'  (string), 'text' (string), 'sign'  (torch. tensor) . This JSON file needs to be both pickled and zipped. The gloss element doesn't take part in the training/test procedure the paper describes, and you can set it to something completely random.

**Comment by avoskou** [comment]
Data example:

[{'name': 'example',
  'signer': 'Unknown',
  'gloss': 'not important random blah blah',
  'text': 'hello world',
  'sign': tensor([[ 0.0345, -0.0241, -1.4745,  ...,  0.1320,  0.1320,  0.1612],
          ...,
          [ 0.0154, -0.0239, -1.4936,  ...,  0.1275,  0.1867,  0.2458]],
         dtype=torch.float64)},
 .....
]

**Comment by avoskou** [comment]
```
#Python function to save the data

import gzip
import pickle

def save(Data,name):
  
  with gzip.open(name, 'wb') as handle:
    pickle.dump(Data, handle, protocol=pickle.HIGHEST_PROTOCOL)
```

**Comment by Danielgol** [comment]
@avoskou I really appreciate your help :)
How can I generate each video's tensors?

Thanks, again!

**Comment by avoskou** [comment]
The model takes as input not the actual video frames but rather a sequence of feature vectors extracted from each one of  the video frames, threrefore the input tensor is  2D (number_of_frames,feature_vector_size) . You need to use some sort of feature extractor, eg a pretrained VGG16, to gain that features.

**Comment by Danielgol** [comment]
Got it! Thanks!
