### ISSUE TITLE
How to use exampleEnsemble.yaml

### ISSUE THREAD

**Issue by pphuc25** [avoskou/Stochastic-Transformer-Networks-with-Linear-Competing-Units-Application-to-end-to-end-SL-Translatio#4]
The issues ``TypeError: stat: path should be string, bytes, os.PathLike or integer, not list`` appear when I try to run ``!python -m signjoey train ./configs/exampleEnsemble.yaml``

Can you show me how to fix it?

**Comment by avoskou** [comment]
Hello,
You can not train an ensemble of models, you can only use this configuration  in test mode to combine(ensemble) a number of indipentedly trained models.

**Comment by pphuc25** [comment]
Thank you so much, Is the idea training the `example.yaml` 5 times with the same parameters and using these in the ensemble of models?

**Comment by avoskou** [comment]
Yes, more or less. You can try same params with diffrent random seeds but you can also try different learning params such learning rate, bacth_size kl_weight etc. If I remember correct the architecture must be tha same.
