### ISSUE TITLE
How to extract the features of sign language frames?

### ISSUE THREAD

**Issue by ZhuPeipei-CUHKSZ-TJUTCM** [avoskou/Stochastic-Transformer-Networks-with-Linear-Competing-Units-Application-to-end-to-end-SL-Translatio#5]
Thanks for your attention! When I use the data "http://cihancamgoz.com/files/cvpr2020/phoenix14t.pami0.train", the experiments can obtain good performance. But, when I extract the features of sign language frames by a pre-trained ResNet50 ckpt, the performance is very worse. 

So, could you help me figure out how to extract the frame features as in "http://cihancamgoz.com/files/cvpr2020/phoenix14t.pami0.train", please?

**Comment by avoskou** [comment]
Hello, the features at http://cihancamgoz.com/files/cvpr2020/phoenix14t.pami0.train were originally introduced in the paper  https://arxiv.org/pdf/2003.13830.pdf. I would recommend reading this paper and reaching out to the authors for any additional clarifications you may require.
